version: '3'
services:
  db:
    image: mysql:5
    restart: always
    environment:
      - MYSQL_PASSWORD=$DATABASE_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DATABASE_PASSWORD
      - MYSQL_USER=$DATABASE_USERNAME
      - MYSQL_DATABASE=$DATABASE_NAME
    ports:
      - $DATABASE_PORT_EXTERNAL:$DATABASE_PORT_INTERNAL

  web:
    image: jonkofee/nginx
    working_dir: /code
    ports:
      - $NGINX_PORT_EXTERNAL:$NGINX_PORT_INTERNAL
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d
    links:
      - php
    environment:
      - DOMAIN=$DOMAIN
      - PHP_PORT=$PHP_PORT

  php:
    build: ./docker/php
    working_dir: /code
    volumes:
      - ./:/code
    links:
      - db
    ports:
      - $PHP_PORT
    environment:
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_PORT=$DATABASE_PORT_INTERNAL
      - DOMAIN=$DOMAIN